### ISSUE TITLE
为什么这里不使用var ,let, const 来声明变量

### ISSUE THREAD

**Issue by zhiqiang21** [zhoulang27426405/learn-promise#1]
https://github.com/zhoulang27426405/learn-promise/blob/8e4eebaef729fd8824c9afd0c397323dac488ba0/stage-4/promise-4.js#L49

如题这里声明为两个全局的变量是起到什么作用呢

**Comment by zhiqiang21** [comment]
额，明白了。这里应该是检查类型，对参数进行重新赋值

**Comment by zhoulang27426405** [comment]
@zhiqiang21 嗯，参考规范2.2.5
